name = "binchen-blog"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "binchen-blog-db"
database_id = "7f97de5c-477b-49bb-85de-7a9d8076652e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "binchen-blog-images"
