# -*- coding: utf-8 -*-
# Slice LXGW WenKai GB Medium into unicode-range woff2 slices + generate @font-face CSS.
import io, os
from fontTools.ttLib import TTFont
from fontTools import subset

SRC = r"C:\Users\binchen\Desktop\code\font\chinese\LXGWWenKaiGB\LXGWWenKaiGB-Medium.ttf"
OUT = r"C:\Users\binchen\Desktop\code\blog\public\fonts"
os.makedirs(OUT, exist_ok=True)

# ---- master charset ----
chars = set(chr(c) for c in range(0x20, 0x7F))                      # ASCII
chars |= set(chr(c) for c in range(0x3000, 0x3040))                 # CJK punctuation
chars |= set(chr(c) for c in range(0xFF00, 0xFF5F))                 # fullwidth forms
chars |= set(u"‒—–‘’“”…·«»‹›")          # dashes/quotes/ellipsis
# GB2312 level-1 hanzi: rows 16-55 (0xB0A1 - 0xD7F9), 3755 chars
for hi in range(0xB0, 0xD8):
    for lo in range(0xA1, 0xFF):
        try:
            chars.add(bytes([hi, lo]).decode("gb2312"))
        except UnicodeDecodeError:
            pass
print("master charset:", len(chars))

# ---- slices ----
slices = []  # (name, unicode-range-desc, charset)
slices.append(("latin", "U+0020-007E", set(chr(c) for c in range(0x20, 0x7F))))
punct = (set(chr(c) for c in range(0x3000, 0x3040))
         | set(chr(c) for c in range(0xFF00, 0xFF5F))
         | set(u"‒—–‘’“”…·«»‹›")) & chars
slices.append(("punct", "U+00B7,U+2000-206F,U+3000-303F,U+FF00-FF5E,U+00AB-00BB", punct))

STEP = 0x140
base = 0x4E00
while base <= 0x9FFF:
    end = min(base + STEP - 1, 0x9FFF)
    cs = set(chr(c) for c in range(base, end + 1)) & chars
    if cs:
        slices.append(("u%04x" % base, "U+%04X-%04X" % (base, end), cs))
    base += STEP

src_font = TTFont(SRC)
css_blocks = []
total = 0
for name, urange, cs in slices:
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.drop_tables += ["FFTM"]
    font = TTFont(SRC)  # fresh load per slice (cheap enough, avoids state bleed)
    ss = subset.Subsetter(options=opts)
    ss.populate(text="".join(sorted(cs)))
    ss.subset(font)
    path = os.path.join(OUT, "lxgw-%s.woff2" % name)
    font.save(path)
    size = os.path.getsize(path)
    total += size
    css_blocks.append(
        "@font-face {\n"
        "  font-family: 'LXGW WenKai GB';\n"
        "  src: url('/fonts/lxgw-%s.woff2') format('woff2');\n"
        "  font-weight: 400 700;\n"
        "  font-style: normal;\n"
        "  font-display: swap;\n"
        "  unicode-range: %s;\n"
        "}" % (name, urange)
    )
    print("%-10s %5d glyphs %8d B" % (name, len(cs), size))

print("TOTAL: %d slices, %d B (was 1828592 B)" % (len(slices), total))

with open(os.path.join(OUT, "lxgw-slices.css"), "w", encoding="ascii") as f:
    f.write("/* generated by slice_lxgw_font.py - do not edit by hand */\n")
    f.write("\n\n".join(css_blocks) + "\n")
print("CSS written to lxgw-slices.css")
